CREATE TABLE IF NOT EXISTS EVENT (
    EVENT_ID TEXT PRIMARY KEY,
    TITLE TEXT,
    START_DATE TEXT,
    ALL_DAY INTEGER
);

CREATE TABLE IF NOT EXISTS EVENT_EXERCISES (
    EVENT_ID TEXT PRIMARY KEY,
    EXERCISE_NAME TEXT PRIMARY KEY,
    EXERCISE_SETS INTEGER,
    EXERCISE_REPS INTEGER,
    EXERICE_WEIGHT INTEGER        
);