CREATE TABLE IF NOT EXISTS EVENT (
    EVENT_ID TEXT PRIMARY KEY,
    TITLE TEXT,
    START_DATE TEXT,
    ALL_DAY INTEGER
);

CREATE TABLE IF NOT EXISTS EVENT_EXERCISES (
    EVENT_ID TEXT,
    EXERCISE_NAME TEXT,
    EXERCISE_SETS INTEGER,
    EXERCISE_REPS INTEGER,
    EXERCISE_WEIGHT INTEGER,
    PRIMARY KEY (EVENT_ID, EXERCISE_NAME)        
);